//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18052.
// 
#pragma warning disable 1591

namespace ERPMercuryImportSuppl.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SOAPServiceSoap", Namespace="http://tempuri.org/")]
    public partial class SOAPService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SaveNewSupplOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSupplStateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSupplItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetChildOrdersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSupplItemsFromInterbaseOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDepartRoutingOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateChangedSupplOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SOAPService() {
            this.Url = global::ERPMercuryImportSuppl.Properties.Settings.Default.ERPMercuryImportSuppl_WebReference_SOAPService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SaveNewSupplCompletedEventHandler SaveNewSupplCompleted;
        
        /// <remarks/>
        public event GetSupplStateCompletedEventHandler GetSupplStateCompleted;
        
        /// <remarks/>
        public event GetSupplItemsCompletedEventHandler GetSupplItemsCompleted;
        
        /// <remarks/>
        public event GetChildOrdersCompletedEventHandler GetChildOrdersCompleted;
        
        /// <remarks/>
        public event GetSupplItemsFromInterbaseCompletedEventHandler GetSupplItemsFromInterbaseCompleted;
        
        /// <remarks/>
        public event GetDepartRoutingCompletedEventHandler GetDepartRoutingCompleted;
        
        /// <remarks/>
        public event UpdateChangedSupplCompletedEventHandler UpdateChangedSupplCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveNewSuppl", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SaveNewSuppl(System.Data.DataSet dsSuppl) {
            object[] results = this.Invoke("SaveNewSuppl", new object[] {
                        dsSuppl});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SaveNewSupplAsync(System.Data.DataSet dsSuppl) {
            this.SaveNewSupplAsync(dsSuppl, null);
        }
        
        /// <remarks/>
        public void SaveNewSupplAsync(System.Data.DataSet dsSuppl, object userState) {
            if ((this.SaveNewSupplOperationCompleted == null)) {
                this.SaveNewSupplOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveNewSupplOperationCompleted);
            }
            this.InvokeAsync("SaveNewSuppl", new object[] {
                        dsSuppl}, this.SaveNewSupplOperationCompleted, userState);
        }
        
        private void OnSaveNewSupplOperationCompleted(object arg) {
            if ((this.SaveNewSupplCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveNewSupplCompleted(this, new SaveNewSupplCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSupplState", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetSupplState(System.Guid SupplGuid) {
            object[] results = this.Invoke("GetSupplState", new object[] {
                        SupplGuid});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetSupplStateAsync(System.Guid SupplGuid) {
            this.GetSupplStateAsync(SupplGuid, null);
        }
        
        /// <remarks/>
        public void GetSupplStateAsync(System.Guid SupplGuid, object userState) {
            if ((this.GetSupplStateOperationCompleted == null)) {
                this.GetSupplStateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSupplStateOperationCompleted);
            }
            this.InvokeAsync("GetSupplState", new object[] {
                        SupplGuid}, this.GetSupplStateOperationCompleted, userState);
        }
        
        private void OnGetSupplStateOperationCompleted(object arg) {
            if ((this.GetSupplStateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSupplStateCompleted(this, new GetSupplStateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSupplItems", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetSupplItems(System.Guid SupplGuid) {
            object[] results = this.Invoke("GetSupplItems", new object[] {
                        SupplGuid});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetSupplItemsAsync(System.Guid SupplGuid) {
            this.GetSupplItemsAsync(SupplGuid, null);
        }
        
        /// <remarks/>
        public void GetSupplItemsAsync(System.Guid SupplGuid, object userState) {
            if ((this.GetSupplItemsOperationCompleted == null)) {
                this.GetSupplItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSupplItemsOperationCompleted);
            }
            this.InvokeAsync("GetSupplItems", new object[] {
                        SupplGuid}, this.GetSupplItemsOperationCompleted, userState);
        }
        
        private void OnGetSupplItemsOperationCompleted(object arg) {
            if ((this.GetSupplItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSupplItemsCompleted(this, new GetSupplItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetChildOrders", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetChildOrders(System.Guid SupplGuid) {
            object[] results = this.Invoke("GetChildOrders", new object[] {
                        SupplGuid});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetChildOrdersAsync(System.Guid SupplGuid) {
            this.GetChildOrdersAsync(SupplGuid, null);
        }
        
        /// <remarks/>
        public void GetChildOrdersAsync(System.Guid SupplGuid, object userState) {
            if ((this.GetChildOrdersOperationCompleted == null)) {
                this.GetChildOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetChildOrdersOperationCompleted);
            }
            this.InvokeAsync("GetChildOrders", new object[] {
                        SupplGuid}, this.GetChildOrdersOperationCompleted, userState);
        }
        
        private void OnGetChildOrdersOperationCompleted(object arg) {
            if ((this.GetChildOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetChildOrdersCompleted(this, new GetChildOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSupplItemsFromInterbase", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetSupplItemsFromInterbase(System.Guid SupplGuid) {
            object[] results = this.Invoke("GetSupplItemsFromInterbase", new object[] {
                        SupplGuid});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetSupplItemsFromInterbaseAsync(System.Guid SupplGuid) {
            this.GetSupplItemsFromInterbaseAsync(SupplGuid, null);
        }
        
        /// <remarks/>
        public void GetSupplItemsFromInterbaseAsync(System.Guid SupplGuid, object userState) {
            if ((this.GetSupplItemsFromInterbaseOperationCompleted == null)) {
                this.GetSupplItemsFromInterbaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSupplItemsFromInterbaseOperationCompleted);
            }
            this.InvokeAsync("GetSupplItemsFromInterbase", new object[] {
                        SupplGuid}, this.GetSupplItemsFromInterbaseOperationCompleted, userState);
        }
        
        private void OnGetSupplItemsFromInterbaseOperationCompleted(object arg) {
            if ((this.GetSupplItemsFromInterbaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSupplItemsFromInterbaseCompleted(this, new GetSupplItemsFromInterbaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDepartRouting", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetDepartRouting(System.Guid DepartGuid, System.DateTime dtBeginDate, System.DateTime dtEndDate) {
            object[] results = this.Invoke("GetDepartRouting", new object[] {
                        DepartGuid,
                        dtBeginDate,
                        dtEndDate});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetDepartRoutingAsync(System.Guid DepartGuid, System.DateTime dtBeginDate, System.DateTime dtEndDate) {
            this.GetDepartRoutingAsync(DepartGuid, dtBeginDate, dtEndDate, null);
        }
        
        /// <remarks/>
        public void GetDepartRoutingAsync(System.Guid DepartGuid, System.DateTime dtBeginDate, System.DateTime dtEndDate, object userState) {
            if ((this.GetDepartRoutingOperationCompleted == null)) {
                this.GetDepartRoutingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDepartRoutingOperationCompleted);
            }
            this.InvokeAsync("GetDepartRouting", new object[] {
                        DepartGuid,
                        dtBeginDate,
                        dtEndDate}, this.GetDepartRoutingOperationCompleted, userState);
        }
        
        private void OnGetDepartRoutingOperationCompleted(object arg) {
            if ((this.GetDepartRoutingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDepartRoutingCompleted(this, new GetDepartRoutingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateChangedSuppl", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet UpdateChangedSuppl(System.Data.DataSet dsChangedSupplList) {
            object[] results = this.Invoke("UpdateChangedSuppl", new object[] {
                        dsChangedSupplList});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateChangedSupplAsync(System.Data.DataSet dsChangedSupplList) {
            this.UpdateChangedSupplAsync(dsChangedSupplList, null);
        }
        
        /// <remarks/>
        public void UpdateChangedSupplAsync(System.Data.DataSet dsChangedSupplList, object userState) {
            if ((this.UpdateChangedSupplOperationCompleted == null)) {
                this.UpdateChangedSupplOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateChangedSupplOperationCompleted);
            }
            this.InvokeAsync("UpdateChangedSuppl", new object[] {
                        dsChangedSupplList}, this.UpdateChangedSupplOperationCompleted, userState);
        }
        
        private void OnUpdateChangedSupplOperationCompleted(object arg) {
            if ((this.UpdateChangedSupplCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateChangedSupplCompleted(this, new UpdateChangedSupplCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SaveNewSupplCompletedEventHandler(object sender, SaveNewSupplCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveNewSupplCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveNewSupplCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetSupplStateCompletedEventHandler(object sender, GetSupplStateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSupplStateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSupplStateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetSupplItemsCompletedEventHandler(object sender, GetSupplItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSupplItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSupplItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetChildOrdersCompletedEventHandler(object sender, GetChildOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetChildOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetChildOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetSupplItemsFromInterbaseCompletedEventHandler(object sender, GetSupplItemsFromInterbaseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSupplItemsFromInterbaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSupplItemsFromInterbaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetDepartRoutingCompletedEventHandler(object sender, GetDepartRoutingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDepartRoutingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDepartRoutingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UpdateChangedSupplCompletedEventHandler(object sender, UpdateChangedSupplCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateChangedSupplCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateChangedSupplCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591